from __future__ import annotations

import argparse
from collections import deque
from pathlib import Path

from planner.grid import Board, load_text_map, parse_level
from planner.region_planner import RegionPlan, build_region_plan

PROJECT_ROOT = Path.cwd() if (Path.cwd() / "main.py").exists() else Path(__file__).resolve().parent
DEFAULT_MAP = PROJECT_ROOT / "examples" / "16x12_hard" / "hard_16x12_high_expand_083.txt"
DEFAULT_HEADER = PROJECT_ROOT / "embedded" / "generated" / "region_ida_example.h"


def export_region_ida_header(
    map_path: str | Path,
    header_path: str | Path = DEFAULT_HEADER,
    *,
    stm32_blocks: bool = True,
) -> Path:
    level = load_text_map(map_path)
    board = parse_level(level)
    plan = build_stm32_block_region_plan(board) if stm32_blocks else build_region_plan(board)
    if len(board.boxes) > 3:
        raise ValueError("STM32 region IDA export currently supports at most 3 boxes.")
    if len(plan.regions) > 20:
        raise ValueError(f"Region count {len(plan.regions)} exceeds PP_MAX_REGIONS=20.")

    header = Path(header_path)
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(_render_header(board, plan, Path(map_path).name), encoding="utf-8")
    return header


def build_stm32_block_region_plan(board: Board) -> RegionPlan:
    """Build a fixed 4x4 block region graph for STM32 export.

    The PC region planner can create many gate regions. For STM32 we use a hard
    cap: each 4-column x 3-row block is one coarse region, so 16x12 maps produce
    exactly 16 possible regions.
    """
    from planner.region_planner import Region

    cell_to_region: dict[tuple[int, int], int] = {}
    region_cells: dict[int, set[tuple[int, int]]] = {i: set() for i in range(16)}
    for row in range(board.rows):
        for col in range(board.cols):
            pos = (row, col)
            if pos in board.walls:
                continue
            region_id = (row // 3) * 4 + (col // 4)
            cell_to_region[pos] = region_id
            region_cells[region_id].add(pos)

    regions = []
    for region_id in range(16):
        cells = region_cells[region_id]
        if not cells:
            continue
        kind = "target" if cells & set(board.goals.values()) else "box" if cells & set(board.boxes.values()) else "block"
        regions.append(Region(region_id, frozenset(cells), kind, tuple()))

    adjacency_sets: dict[int, set[int]] = {region.region_id: set() for region in regions}
    for (row, col), region_id in cell_to_region.items():
        for nxt in ((row - 1, col), (row + 1, col), (row, col - 1), (row, col + 1)):
            other = cell_to_region.get(nxt)
            if other is not None and other != region_id:
                adjacency_sets[region_id].add(other)

    from planner.region_planner import _target_motions

    adjacency = {rid: tuple(sorted(neighbors)) for rid, neighbors in adjacency_sets.items()}
    motions = tuple(_target_motions(board, cell_to_region, adjacency))
    return RegionPlan(tuple(regions), cell_to_region, adjacency, motions, ("STM32 4x3 block region graph.",))


def _render_header(board: Board, plan: RegionPlan, source_name: str) -> str:
    region_ids = [0xFF] * (board.rows * board.cols)
    for pos, region_id in plan.cell_to_region.items():
        region_ids[_cell(pos)] = region_id

    adj_rows = []
    for region_id in range(20):
        neighbors = list(plan.adjacency.get(region_id, ()))[:4]
        neighbors.extend([0xFF] * (4 - len(neighbors)))
        adj_rows.append(neighbors)

    deadlock = _corner_deadlock(board)
    region_dist = _region_distance_matrix(plan)
    goal_cells = [_cell(board.goals[i + 1]) if i + 1 in board.goals else 0xFF for i in range(3)]
    boxes = [_cell(board.boxes[i + 1]) if i + 1 in board.boxes else goal_cells[i] for i in range(3)]
    player = _cell(board.player)
    target_regions = [
        plan.cell_to_region[board.goals[i + 1]] if i + 1 in board.goals else 0xFF
        for i in range(3)
    ]

    lines = [
        "/* Auto-generated by export_region_ida.py. Do not edit by hand. */",
        f"/* Source map: {source_name} */",
        "#ifndef SMART_CAR_REGION_IDA_EXAMPLE_H",
        "#define SMART_CAR_REGION_IDA_EXAMPLE_H",
        "",
        '#include "../stm32f304/region_ida.h"',
        "",
        f"#define REGION_IDA_EXAMPLE_REGION_COUNT {len(plan.regions)}u",
        "",
        f"static const pp_state_t region_ida_example_start = 0x{_pack(player, boxes):08X}u;",
        "static const uint8_t region_ida_example_goals[PP_MAX_BOXES] = { "
        + ", ".join(f"{cell}u" for cell in goal_cells)
        + " };",
        "",
        "static const pp_region_graph_t region_ida_example_graph = {",
        "    .region_id = {",
        _format_array(region_ids, per_line=16, indent="        "),
        "    },",
        "    .adj = {",
    ]
    for row in adj_rows:
        lines.append("        { " + ", ".join(_u8(value) for value in row) + " },")
    lines.extend([
        "    },",
        f"    .region_count = {len(plan.regions)}u,",
        "    .box_target_region = { " + ", ".join(_u8(value) for value in target_regions) + " },",
        "    .deadlock = {",
        _format_array(deadlock, per_line=16, indent="        "),
        "    },",
        "    .region_dist = {",
    ])
    for row in region_dist:
        lines.append("        { " + ", ".join(_u8(value) for value in row) + " },")
    lines.extend([
        "    },",
        "};",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def _corner_deadlock(board: Board) -> list[int]:
    result = [0] * (board.rows * board.cols)
    goals = set(board.goals.values())
    for row in range(board.rows):
        for col in range(board.cols):
            pos = (row, col)
            if pos in board.walls or pos in goals:
                continue
            up = row == 0 or (row - 1, col) in board.walls
            down = row == board.rows - 1 or (row + 1, col) in board.walls
            left = col == 0 or (row, col - 1) in board.walls
            right = col == board.cols - 1 or (row, col + 1) in board.walls
            if (up and left) or (up and right) or (down and left) or (down and right):
                result[_cell(pos)] = 1
    return result


def _region_distance_matrix(plan: RegionPlan) -> list[list[int]]:
    matrix = [[0xFF for _ in range(20)] for _ in range(20)]
    for start in range(len(plan.regions)):
        matrix[start][start] = 0
        queue: deque[int] = deque([start])
        while queue:
            cur = queue.popleft()
            for nxt in plan.adjacency.get(cur, ()):
                if matrix[start][nxt] == 0xFF:
                    matrix[start][nxt] = matrix[start][cur] + 1
                    queue.append(nxt)
    return matrix


def _cell(pos: tuple[int, int]) -> int:
    return pos[0] * 16 + pos[1]


def _pack(player: int, boxes: list[int]) -> int:
    return (player << 24) | (boxes[0] << 16) | (boxes[1] << 8) | boxes[2]


def _u8(value: int) -> str:
    return "PP_REGION_INVALID" if value == 0xFF else f"{value}u"


def _format_array(values: list[int], *, per_line: int, indent: str) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append(indent + ", ".join(_u8(value) for value in chunk) + ",")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export STM32 region-guided IDA* data.")
    parser.add_argument("--map", default=str(DEFAULT_MAP), help="Input 16x12 map text file.")
    parser.add_argument("--header", default=str(DEFAULT_HEADER), help="Output C header path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    header = export_region_ida_header(args.map, args.header)
    print(f"Exported {header}")


if __name__ == "__main__":
    main()
