from __future__ import annotations

import argparse
import json
from pathlib import Path

from planner.complex_maps import all_complex_levels
from planner.grid import Board, Position, parse_level
from planner.levels import COLS, ROWS
from planner.solver import solve

PROJECT_ROOT = Path(__file__).resolve().parent
GENERATED_DIR = PROJECT_ROOT / "embedded" / "generated"
DEFAULT_HEADER = GENERATED_DIR / "stm32_plans.h"
DEFAULT_REPORT = GENERATED_DIR / "stm32_memory_report.json"

DIR_NAMES = {
    "l": "PP_DIR_LEFT",
    "u": "PP_DIR_UP",
    "d": "PP_DIR_DOWN",
    "r": "PP_DIR_RIGHT",
}


def export_stm32_plans(
    *,
    header_path: str | Path = DEFAULT_HEADER,
    report_path: str | Path = DEFAULT_REPORT,
) -> tuple[Path, Path]:
    header = Path(header_path)
    report = Path(report_path)
    header.parent.mkdir(parents=True, exist_ok=True)
    report.parent.mkdir(parents=True, exist_ok=True)

    plan_entries = []
    reports = []
    for level in all_complex_levels():
        board = parse_level(level)
        result = solve(board)
        if not result.solved:
            raise RuntimeError(f"Level {level.level_id} failed: {result.message}")
        encoded_actions = [
            _encode_action(
                action,
                result.steps[index + 1] if index + 1 < len(result.steps) else None,
                is_recognition=index < result.recognition_cost,
            )
            for index, action in enumerate(result.actions)
        ]
        if len(encoded_actions) > 128:
            raise RuntimeError(f"Level {level.level_id} has {len(encoded_actions)} actions, exceeds PP_MAX_ACTIONS")
        wall_words = _wall_words(board)
        symbol = f"stm32_plan_{level.level_id}"
        plan_entries.append(
            {
                "level_id": level.level_id,
                "symbol": symbol,
                "actions": encoded_actions,
                "wall_words": wall_words,
                "total_cost": result.total_cost,
                "recognition_cost": result.recognition_cost,
                "pushes": result.pushes,
            }
        )
        reports.append(
            {
                "level_id": level.level_id,
                "action_count": len(encoded_actions),
                "wall_bytes": len(wall_words) * 4,
                "action_bytes": len(encoded_actions),
                "recognition_cost": result.recognition_cost,
                "total_cost": result.total_cost,
                "pushes": result.pushes,
                "explosion_count": sum(1 for step in result.steps if step.explosions),
            }
        )

    header.write_text(_render_header(plan_entries), encoding="utf-8")
    report.write_text(json.dumps(_render_report(reports), indent=2, ensure_ascii=False), encoding="utf-8")
    return header, report


def _encode_action(action: str, step_after=None, *, is_recognition: bool = False) -> str:
    move_kind = "PP_KIND_SCAN_MOVE" if is_recognition else "PP_KIND_MOVE"
    if action == "turn_left":
        direction = DIR_NAMES[(step_after.heading or "L").lower()]
        return f"(PP_ACTION({direction}, {move_kind}) | PP_ACTION_TURN_LEFT)"
    if action == "turn_right":
        direction = DIR_NAMES[(step_after.heading or "R").lower()]
        return f"(PP_ACTION({direction}, {move_kind}) | PP_ACTION_TURN_RIGHT)"
    if action == "forward":
        direction = DIR_NAMES[(step_after.heading or "R").lower()]
        return f"PP_ACTION({direction}, {move_kind})"
    if action.startswith("scan_"):
        direction = DIR_NAMES[action[-1]]
        return f"PP_ACTION({direction}, PP_KIND_SCAN_MOVE)"
    if action.startswith("x") or action.startswith("X"):
        direction = DIR_NAMES[action[-1].lower()]
        flag = " | PP_ACTION_EXPLODE" if action.startswith("X") else ""
        return f"(PP_ACTION({direction}, PP_KIND_PUSH_BOMB){flag})"
    if len(action) == 1 and action.islower():
        direction = DIR_NAMES[action]
        return f"PP_ACTION({direction}, PP_KIND_MOVE)"
    if len(action) == 1 and action.isupper():
        direction = DIR_NAMES[action.lower()]
        return f"PP_ACTION({direction}, PP_KIND_PUSH_BOX)"
    raise ValueError(f"Unsupported action for STM32 export: {action!r}")


def _wall_words(board: Board) -> list[int]:
    words = [0] * ((board.rows * board.cols + 31) // 32)
    for row, col in board.walls:
        index = row * board.cols + col
        words[index >> 5] |= 1 << (index & 31)
    return words


def _render_header(plan_entries: list[dict]) -> str:
    lines = [
        "/* Auto-generated by export_stm32.py. Do not edit by hand. */",
        "#ifndef SMART_CAR_STM32_PLANS_H",
        "#define SMART_CAR_STM32_PLANS_H",
        "",
        '#include "../stm32f304/planner_core.h"',
        "",
        "#if defined(__GNUC__)",
        "#define STM32_PLANS_MAYBE_UNUSED __attribute__((unused))",
        "#else",
        "#define STM32_PLANS_MAYBE_UNUSED",
        "#endif",
        "",
    ]
    for entry in plan_entries:
        action_values = ", ".join(entry["actions"])
        lines.append(f"static const uint8_t {entry['symbol']}_actions[] = {{")
        lines.append(f"    {action_values}")
        lines.append("};")
        lines.append("")

    lines.append(f"#define STM32_PLAN_COUNT {len(plan_entries)}u")
    lines.append("static const pp_plan_t stm32_plans[STM32_PLAN_COUNT] STM32_PLANS_MAYBE_UNUSED = {")
    for entry in plan_entries:
        wall_values = ", ".join(f"0x{word:08X}u" for word in entry["wall_words"])
        lines.append("    {")
        lines.append(f"        .level_id = {entry['level_id']}u,")
        lines.append("        .rows = PP_ROWS,")
        lines.append("        .cols = PP_COLS,")
        lines.append(f"        .action_count = {len(entry['actions'])}u,")
        lines.append(f"        .recognition_cost = {entry['recognition_cost']}u,")
        lines.append(f"        .total_cost = {entry['total_cost']}u,")
        lines.append(f"        .pushes = {entry['pushes']}u,")
        lines.append(f"        .wall_bits = {{ {wall_values} }},")
        lines.append(f"        .actions = {entry['symbol']}_actions,")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#undef STM32_PLANS_MAYBE_UNUSED")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def _render_report(reports: list[dict]) -> dict:
    plan_flash_bytes = sum(item["wall_bytes"] + item["action_bytes"] for item in reports)
    cell_count = ROWS * COLS
    bfs_workspace_ram = cell_count * 2 + cell_count * 2 + cell_count
    runner_ram = 8
    return {
        "target": "STM32F304 fixed-memory planner",
        "grid": "16x12",
        "plan_count": len(reports),
        "max_actions_per_plan": max(item["action_count"] for item in reports),
        "estimated_static_flash_bytes_for_plans": plan_flash_bytes,
        "estimated_bfs_workspace_ram_bytes": bfs_workspace_ram,
        "estimated_runner_ram_bytes": runner_ram,
        "estimated_total_runtime_ram_bytes": bfs_workspace_ram + runner_ram,
        "notes": [
            "Full Python A* is not intended to run on STM32F304.",
            "STM32 firmware replays exported actions and can run fixed-array BFS for local correction.",
            "No malloc, recursion, OpenCV, Tkinter, dict, or heap is required on MCU.",
        ],
        "levels": reports,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export embedded STM32F304 plan arrays.")
    parser.add_argument("--header", default=str(DEFAULT_HEADER), help="Output C header path.")
    parser.add_argument("--report", default=str(DEFAULT_REPORT), help="Output JSON memory report path.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    header, report = export_stm32_plans(header_path=args.header, report_path=args.report)
    print(f"Exported {header}")
    print(f"Exported {report}")


if __name__ == "__main__":
    main()
